Heroku added time offset + confirmation on dyno not using credit when sleeping
am-steph/genshin-impact-helper pull request #5
Opened 2021-05-22 00:31 UTC by huizichin

i used to host discord bot on heroku and it doesnt use credit when it is not active (called by discord api)
this also goes to this script it did not use any credit so it shouldnt be a worry, it would only use credit during the check in operation which only take a few seconds
![image](https://user-images.githubusercontent.com/16850884/119209134-a726b980-bad7-11eb-87ce-38c02636be97.png)
here is a image after having it running for a days(since yesterday i created that pull request

2021-05-23 03:25 UTC, am-steph commented
![image](https://user-images.githubusercontent.com/80233054/119246967-f6123480-bb53-11eb-8020-fd7ec6e7ddb7.png)
It notes here that apps that only utilize a free worker dyno don't sleep. I'm hosting a bot currently on Heroku and I can tell you that it does consume hours. 
![image](https://user-images.githubusercontent.com/80233054/119247083-e9daa700-bb54-11eb-8cf8-a2bc244be1a7.png)

2021-05-23 04:03 UTC, am-steph commented on main.py
>      exec(open('./run.py').read())
run.py has random sleep, if you are adding random sleep in main.py, just directly execute genshin-os.py

2021-05-23 04:03 UTC, am-steph requested changes
change run.py to genshin-os.py

2021-05-23 04:15 UTC, am-steph commented on main.py
>  print("Script Started")
Missing loop to run pending, it'll crash after printing this line

2021-05-23 05:37 UTC, huizichin commented
weird enough tho it is not counting it into credit i have this running for 2 days
![image](https://user-images.githubusercontent.com/16850884/119249555-f9e19d80-bbcb-11eb-8a98-88e6aa158a70.png)

2021-05-23 05:37 UTC, huizichin commented on main.py
>  print("Script Started")
there is loop?

2021-05-23 07:02 UTC, huizichin commented
nvm it did charge me just took them forever to update
![image](https://user-images.githubusercontent.com/16850884/119251182-c60c7500-bbd7-11eb-90c2-d915ce0561df.png)
here i updated it to use sleep only instead of that scheduler thingy uhh hopefully it work

2021-05-24 02:27 UTC, huizichin commented
hmm it doesnt seem to work
it did send the webhook which is good it mean it triggered when i wanted it to but it showed this
![image](https://user-images.githubusercontent.com/16850884/119288194-ac703980-bc7a-11eb-8b15-66b1860fdf54.png)

2021-05-24 11:08 UTC, huizichin commented
and it still charged me
![image](https://user-images.githubusercontent.com/16850884/119339124-67242a00-bcc3-11eb-8e00-1be41ca44b20.png)
though my discord bot seem to not been using much time tho weird

2021-05-26 23:29 UTC, am-steph commented
You could continue trying to get Heroku dyno working, but I think its just easier to use Wayscript for those looking for a free method and its much easier to set up. Otherwise Heroku Scheduler is better to use to run on off scripts like this.

2021-05-26 23:29 UTC, closed without merging